# Generated by generate_models.sh. Do not edit by hand.
"""Provenance metadata for the regenerated UCP schema models."""

# Commit SHA on Universal-Commerce-Protocol/ucp the models were generated from.
UCP_SCHEMA_REF = "c5c61396ebf9a5afb9c4169bfa3af1409daa6fd6"

# generate_models.sh invocation that produced the current tree.
GENERATE_COMMAND = (
    "generate_models.sh --ref c5c61396ebf9a5afb9c4169bfa3af1409daa6fd6"
)
