#!/bin/bash
# Generate Pydantic models from UCP JSON Schemas

set -euo pipefail

# Ensure we are in the script's directory
cd "$(dirname "$0")"

# Add ~/.local/bin to PATH for uv
export PATH="$HOME/.local/bin:$PATH"

# Check if git is installed
if ! command -v git &> /dev/null; then
    echo "Error: git not found. Please install git." >&2
    exit 1
fi

# UCP source selection — three modes:
#   ./generate_models.sh                  # main branch
#   ./generate_models.sh 2026-04-08       # release/2026-04-08 branch
#   ./generate_models.sh --ref <sha|ref>  # arbitrary commit/branch/tag
#
# Identity-linking, info_code, and warning_code schemas merged after the
# 2026-04-08 release branch was cut, so consumers needing those must pin
# an explicit ref via --ref.
REF_MODE=""
REF_VALUE=""
if [ "${1:-}" = "--ref" ]; then
    if [ -z "${2:-}" ]; then
        echo "Error: --ref requires a commit SHA, branch, or tag." >&2
        exit 1
    fi
    REF_MODE="ref"
    REF_VALUE="$2"
    echo "Cloning ucp at ref $REF_VALUE..."
elif [ -z "${1:-}" ]; then
    REF_MODE="branch"
    REF_VALUE="main"
    echo "No version specified, cloning main branch..."
else
    REF_MODE="branch"
    REF_VALUE="release/$1"
    echo "Cloning version $1 (branch: $REF_VALUE)..."
fi

# Ensure ucp directory is clean before cloning
rm -rf ucp
if [ "$REF_MODE" = "ref" ]; then
    # Arbitrary ref may not be reachable via shallow clone of a branch;
    # do a full clone, then check out the ref. With set -e, a failed
    # checkout (bad SHA, missing tag, network blip) aborts the script
    # before any regen runs.
    git clone https://github.com/Universal-Commerce-Protocol/ucp ucp
    git -C ucp checkout "$REF_VALUE"
    git -C ucp rev-parse --verify HEAD >/dev/null
else
    git clone -b "$REF_VALUE" --depth 1 https://github.com/Universal-Commerce-Protocol/ucp ucp
fi

# Resolve the actual commit SHA we ended up on (for provenance manifest below)
UCP_SCHEMA_REF="$(git -C ucp rev-parse HEAD)"
echo "ucp HEAD: $UCP_SCHEMA_REF"

# Output directory
OUTPUT_DIR="src/ucp_sdk/models/schemas"

# Schema directory (relative to this script)
SCHEMA_DIR="ucp/source/schemas"

echo "Preprocessing schemas..."
uv run python preprocess_schemas.py

echo "Generating Pydantic models from preprocessed schemas..."

# Check if uv is installed
if ! command -v uv &> /dev/null; then
    echo "Error: uv not found." >&2
    echo "Please install uv: curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
    exit 1
fi

# Ensure output directory is clean
rm -r -f "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"


# Run generation using uv
# We use --use-schema-description to use descriptions from JSON schema as docstrings
# We use --field-constraints to include validation constraints (regex, min/max, etc.)
# Note: Formatting is done as a post-processing step.
uv run \
    --link-mode=copy \
    --extra-index-url https://pypi.org/simple python \
    -m datamodel_code_generator \
    --input "$SCHEMA_DIR" \
    --input-file-type jsonschema \
    --output "$OUTPUT_DIR" \
    --output-model-type pydantic_v2.BaseModel \
    --use-schema-description \
    --field-constraints \
    --use-field-description \
    --enum-field-as-literal all \
    --disable-timestamp \
    --use-double-quotes \
    --no-use-annotated \
    --allow-extra-fields \
    --custom-template-dir templates \
    --additional-imports pydantic.ConfigDict


echo "Formatting generated models..."
uv run ruff format
# Match the project's pre-commit ignore list (`.pre-commit-config.yaml`):
# auto-generated docstrings legitimately exceed line length and miss
# Google-style sections. Without these ignores, set -e would abort the
# whole regen on a benign lint diff.
uv run ruff check --fix --ignore "D,E501" "$OUTPUT_DIR"

# Normalize end-of-file on every generated module: codegen emits a
# trailing blank line that pre-commit's end-of-file-fixer strips on the
# next run, dirtying the working tree on every regen. Collapse trailing
# blank lines to exactly one newline up front.
uv run python <<'PY'
from pathlib import Path

for path in Path("src/ucp_sdk/models/schemas").rglob("*.py"):
    text = path.read_text(encoding="utf-8")
    stripped = text.rstrip("\n")
    if stripped + "\n" != text:
        path.write_text(stripped + "\n", encoding="utf-8")
PY


# Record the source ref that produced this generated tree, so downstream
# consumers can verify provenance after upstream main moves. Format below
# is chosen to round-trip through ruff format / ruff check unchanged.
GEN_CMD="$0 $*"
if [ -z "$*" ]; then
    GEN_CMD="$0"
fi
cat > "src/ucp_sdk/_schema_ref.py" <<EOF
# Generated by generate_models.sh. Do not edit by hand.
"""Provenance metadata for the regenerated UCP schema models."""

# Commit SHA on Universal-Commerce-Protocol/ucp the models were generated from.
UCP_SCHEMA_REF = "$UCP_SCHEMA_REF"

# generate_models.sh invocation that produced the current tree.
GENERATE_COMMAND = "$GEN_CMD"
EOF
# Re-format _schema_ref.py so the committed file matches what ruff would
# do on its own — without this, a long --ref or invocation can produce a
# line that ruff format would later wrap, putting the working tree out
# of sync with future regens.
uv run ruff format src/ucp_sdk/_schema_ref.py
echo "Wrote provenance to src/ucp_sdk/_schema_ref.py: $UCP_SCHEMA_REF"


echo "Done. Models generated in $OUTPUT_DIR"
